#! /usr/bin/env php

<?php

use Supercli\CreateVhostCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Super CLI','1.0');

$app->add(new CreateVhostCommand());

$app->run();
